/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.chuyenmanhinhcontroller;


/**
 *
 * @author lehie
 */
public class ThongKeJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
        chuyenmanhinhcontroller c = new chuyenmanhinhcontroller(jPanelthongke);
        c.setview(new ThongKeTH());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelthongke = new javax.swing.JPanel();
        cbtk = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ");

        jPanelthongke.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanelthongkeLayout = new javax.swing.GroupLayout(jPanelthongke);
        jPanelthongke.setLayout(jPanelthongkeLayout);
        jPanelthongkeLayout.setHorizontalGroup(
            jPanelthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelthongkeLayout.setVerticalGroup(
            jPanelthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        cbtk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thống kê tổng hợp", "Thống kê nhân viên", "Thống kê khách hàng" }));
        cbtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
            .addComponent(jPanelthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtkActionPerformed
        int index = cbtk.getSelectedIndex();
        if(index >= 0){
            if(index == 0)
            {
                chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanelthongke);
                controller.setview(new ThongKeTH());
            }
            if(index == 1)
            {
                chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanelthongke);
                controller.setview(new ThongKeNV());
            }
            if(index == 2)
            {
                chuyenmanhinhcontroller controller = new chuyenmanhinhcontroller(jPanelthongke);
                controller.setview(new ThongKeKH());
            }
        }
    }//GEN-LAST:event_cbtkActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbtk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelthongke;
    // End of variables declaration//GEN-END:variables
}
