/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Class.DangNhap;
import Database.DBconnect;
import Interface.Table;

/**
 *
 * @author lehie
 */
public class UserJPanel extends javax.swing.JPanel implements Table{
    DBconnect db = new DBconnect();
    int pos = 0;
    DangNhap x = new DangNhap();
    
    /**
     * Creates new form UserJPanel
     */
    public UserJPanel() {
        initComponents();
        this.jbnsua.setEnabled(false);
        this.jbnxoa.setEnabled(false);
        showt();
    }
    private void showt(){
        db = new DBconnect();
        db.getconnect();
        db.getResult("select * from NGUOIDUNG");
        db.connectdangnhap();
        db.view_table_dangnhap(tbltk, db.dn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtk = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txmk = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbnsua = new javax.swing.JButton();
        jbnxoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbq = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttnv = new javax.swing.JTextField();
        txcmnd = new javax.swing.JTextField();
        rbtn = new javax.swing.JRadioButton();
        rbtnu = new javax.swing.JRadioButton();
        panel4 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltk = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tài khoản:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu:");

        jScrollPane1.setViewportView(txtk);

        jScrollPane2.setViewportView(txmk);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/manage_accounts_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel3.setText("Người Dùng");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbnsua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbnsua.setText("Sửa");
        jbnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnsuaActionPerformed(evt);
            }
        });

        jbnxoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbnxoa.setText("Xóa");
        jbnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnxoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Quyền :");

        cbq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Nhân viên", "Quản kho" }));

        jLabel6.setText("Họ và tên :");
        jLabel6.setToolTipText("");

        jLabel7.setText("CMND :");

        jLabel8.setText("Giới tính:");

        rbtn.setSelected(true);
        rbtn.setText("nam");
        rbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnMouseClicked(evt);
            }
        });

        rbtnu.setText("nữ");
        rbtnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnsua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbnxoa)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(cbq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txttnv)
                        .addComponent(txcmnd, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(rbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txttnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txcmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(rbtn)
                    .addComponent(rbtnu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jbnsua)
                    .addComponent(jbnxoa))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        tbltk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Quyền", "Họ và tên ", "CMND", "Giới tính"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbltk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltk);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách tài khoản");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private String getmaq(){
        String maq= "";
        if(((String) cbq.getSelectedItem()).equals("Quản lý")){
            maq = "QL";
        }
        else if(((String) cbq.getSelectedItem()).equals("Nhân viên")){
            maq = "NV";
        }
        else if(((String) cbq.getSelectedItem()).equals("Quản kho")){
            maq = "QK";
        }
        else {maq = "NV";}
        return maq;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.chucnang("exec themnguoidung '"+this.txtk.getText()+"','"+this.txmk+"','"+this.getmaq()+"',N'"+this.txttnv.getText()+"','"+this.txcmnd.getText()+"',N'"+db.getstgioitinh(rbtn)+"'");
        this.jbnsua.setEnabled(false);
        this.jbnxoa.setEnabled(false);
        showt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnsuaActionPerformed
        db.chucnang("exec capnhapnguoidung '"+this.txtk.getText()+"','"+this.txmk+"','"+this.getmaq()+"',N'"+this.txttnv.getText()+"','"+this.txcmnd.getText()+"',N'"+db.getstgioitinh(rbtn)+"'");
        this.jbnsua.setEnabled(false);
        this.jbnxoa.setEnabled(false);
        showt();
    }//GEN-LAST:event_jbnsuaActionPerformed

    private void rbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnMouseClicked
        this.rbtnu.setSelected(false);
    }//GEN-LAST:event_rbtnMouseClicked

    private void rbtnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnuMouseClicked
        this.rbtn.setSelected(false);
    }//GEN-LAST:event_rbtnuMouseClicked

    private void jbnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnxoaActionPerformed
        db.chucnang("delete from NGUOIDUNG WHERE TAIKHOAN = '"+this.txtk.getText()+"'");
        this.jbnsua.setEnabled(false);
        this.jbnxoa.setEnabled(false);
        showt();
    }//GEN-LAST:event_jbnxoaActionPerformed

    private void tbltkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltkMouseClicked
        this.pos = this.tbltk.getSelectedRow();
        this.jbnsua.setEnabled(true);
        this.jbnxoa.setEnabled(true);
        view();
    }//GEN-LAST:event_tbltkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbq;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbnsua;
    private javax.swing.JButton jbnxoa;
    private java.awt.Panel panel1;
    private java.awt.Panel panel4;
    private javax.swing.JRadioButton rbtn;
    private javax.swing.JRadioButton rbtnu;
    private javax.swing.JTable tbltk;
    private javax.swing.JTextField txcmnd;
    private javax.swing.JTextPane txmk;
    private javax.swing.JTextPane txtk;
    private javax.swing.JTextField txttnv;
    // End of variables declaration//GEN-END:variables


    private void view() {
        x = db.dn.get(pos);
        this.txtk.setText(x.getTaikhoan());
        this.txmk.setText(x.getMatkhau());
        this.txcmnd.setText(x.getCmnd());
        this.txttnv.setText(x.getTennv());
        if(x.getGioitinh().equals("Nam")==true){
            this.rbtn.setSelected(true);
            this.rbtnu.setSelected(false);
        }
        else{
            this.rbtn.setSelected(false);
            this.rbtnu.setSelected(true);
        }
        if(x.getMaq().equals("QL")){
            this.cbq.setSelectedItem("Quản lý");
        }
        else if(x.getMaq().equals("NV")){
            this.cbq.setSelectedItem("Nhân viên");
        }
        else if(x.getMaq().equals("QK")){
            this.cbq.setSelectedItem("Quản kho");
        }
    }
}
